name: Pull request develop

on:
  pull_request:
    branches: 
      [develop]
      
concurrency:
  group: ci-pipenv-catalog-service-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Cambia a "3.9.6" si tu Pipfile/Pipfile.lock lo exige
        python-version: ["3.12"]

    # Todo se ejecuta desde la subcarpeta catalog-service
    defaults:
      run:
        working-directory: ./catalog-service

    env:
      PIPENV_VENV_IN_PROJECT: "1"
      PIPENV_NOSPIN: "1"
      PIPENV_HIDE_EMOJIS: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip & install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install "pipenv>=2023.0.0"

      # Cache de pip (ruedas/wheels)
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('catalog-service/Pipfile.lock') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ matrix.python-version }}-

      # Cache del entorno virtual del proyecto
      - name: Cache .venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: catalog-service/.venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('catalog-service/Pipfile.lock') }}

      # Vincula Pipenv al intérprete instalado por setup-python
      - name: Bind Pipenv to runner Python
        run: |
          pipenv --python "$(python -c 'import sys; print(sys.executable)')"
          pipenv --venv

      # Instala dependencias usando el lock
      - name: Install deps with Pipenv
        run: |
          if [ ! -f Pipfile.lock ]; then
            echo "::error::Falta catalog-service/Pipfile.lock. Ejecuta: (cd catalog-service && pipenv lock) y súbelo."
            exit 1
          fi
          pipenv sync --dev --bare --verbose

      - name: Show environment
        run: |
          python --version
          pipenv --py
          pipenv --venv
          pipenv graph

      - name: Run tests (pytest + coverage)
        run: |
          pipenv run python -m pytest -q \
            --junitxml=pytest.xml \
            --cov=. --cov-report=xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.python-version }}
          path: catalog-service/pytest.xml

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-${{ matrix.python-version }}
          path: catalog-service/coverage.xml
